apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: llm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: grafana-credentials
    creationPolicy: Owner
  data:
    - secretKey: grafanapassword  
      remoteRef:
        key: llm-secrets 
        version: "AWSCURRENT"
        property: grafanapassword 
    