apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret
  namespace: llm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: secrets-manager-secret
    creationPolicy: Owner
  data:
    - secretKey: postgrespassword    #name of the secret key
      remoteRef:
        key:  postgres-secret # secret name in gcp
        version: "AWSCURRENT"
        property: postgrespassword # JSON property

    - secretKey: hostname    
      remoteRef:
        key:  postgres-secret 
        version: "AWSCURRENT"
        property: hostname

    - secretKey: openaikey    
      remoteRef:
        key: llm-secrets  
        version: "AWSCURRENT"
        property: openaikey 

---


apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: elasticsearch-master-credentials
  namespace: llm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: elasticsearch-master-credentials
    creationPolicy: Owner
  data:
    - secretKey: username    
      remoteRef:
        key: llm-secrets  
        version: "AWSCURRENT"
        property: elasticusername 
    - secretKey: password   
      remoteRef:
        key: llm-secrets 
        version: "AWSCURRENT"
        property: elasticpassword 

