apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: search-application
   namespace: argocd
   finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  project: llm-project
  destination:
    server: https://kubernetes.default.svc
    namespace: llm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://helm.elastic.co
      chart: elasticsearch
      targetRevision: 8.5.1
      helm:
        valueFiles:
          - $values/infrastructure/kubernetes/manifests/elastic-search/master-helm/elastic-master.yaml
    - repoURL: git@github.com:OLAMIDE100/Capstone-Project-LLM-ZoomCamp.git
      ref: values
      targetRevision: main

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: data-search-application
   namespace: argocd
   finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  project: llm-project
  destination:
    server: https://kubernetes.default.svc
    namespace: llm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://helm.elastic.co
      chart: elasticsearch
      targetRevision: 8.5.1
      helm:
        valueFiles:
          - $values/infrastructure/kubernetes/manifests/elastic-search/data-helm/elastic-data.yaml
    - repoURL: git@github.com:OLAMIDE100/Capstone-Project-LLM-ZoomCamp.git
      ref: values
      targetRevision: main

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: client-search-application
   namespace: argocd
   finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  project: llm-project
  destination:
    server: https://kubernetes.default.svc
    namespace: llm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://helm.elastic.co
      chart: elasticsearch
      targetRevision: 8.5.1
      helm:
        valueFiles:
          - $values/infrastructure/kubernetes/manifests/elastic-search/client-helm/elastic-client.yaml
    - repoURL: git@github.com:OLAMIDE100/Capstone-Project-LLM-ZoomCamp.git
      ref: values
      targetRevision: main

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: kibana-application
   namespace: argocd
   finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  project: llm-project
  destination:
    server: https://kubernetes.default.svc
    namespace: llm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://helm.elastic.co
      chart: kibana
      targetRevision: 8.5.1
      helm:
        valueFiles:
          - $values/infrastructure/kubernetes/manifests/elastic-search/kibana/kibana.yaml
    - repoURL: git@github.com:OLAMIDE100/Capstone-Project-LLM-ZoomCamp.git
      ref: values
      targetRevision: main