apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  refreshInterval: 0s         
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager    
  target:
    name: argocd-secret 
    creationPolicy: Owner
  data:
    - secretKey: admin.password  
      remoteRef:
        key: argocd 
        version: "AWSCURRENT"
        property: password

    - secretKey: server.secretkey  
      remoteRef:
        key: argocd 
        version: "AWSCURRENT"
        property: server-key