apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  refreshInterval: 0s         
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager    
  target:
    name: argocd-secret 
    creationPolicy: Owner
  data:
    - secretKey: admin.password  
      remoteRef:
        key: argocd 
        version: "AWSCURRENT"
        property: password

    - secretKey: server.secretkey  
      remoteRef:
        key: argocd 
        version: "AWSCURRENT"
        property: server-key

---


apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-creds-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/instance: argocd
    pp.kubernetes.io/managed-by: Helm
  annotations:
   "meta.helm.sh/release-namespace" : default
spec:
  refreshInterval: 0s         
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager    
  target:
    name: argocd-repo-creds-ssh
    creationPolicy: Owner
  data:
    - secretKey: url 
      remoteRef:
        key: argocd 
        version: "AWSCURRENT"
        property: url

    - secretKey: sshPrivateKey  
      remoteRef:
        key: sshPrivateKey
        version: "AWSCURRENT"
