name: 'deployment_job'

on:
  push:
    branches:
     - "main"
    paths:
     - 'infrastructure/terraform/**'
     - 'infrastructure/kubernetes/**'
   

jobs:
  Cloud_Resources_Deployment:
    name: 'Cloud_Resources_Deployment'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Detect_Changes
      uses: dorny/paths-filter@v2
      id: changes
      with:

        base: 'main'

        filters: |
          terraform:
            - 'infrastructure/terraform/**'
          kubernetes:
            - 'infrastructure/kubernetes/**'

    - name: Setup_Terraform
      uses: hashicorp/setup-terraform@v1

    - name: terraform
      if: steps.changes.outputs.terraform == 'true' 
      run: |
            echo "this terraform specific deployment"
            pwd
            ls

    - name: kubernetes
      if: steps.changes.outputs.kubernetes == 'true' 
      run: |
            echo "this kubernetes specific deployment"
            pwd
            ls

    