name: 'deployment_job'

on:
  push:
    branches:
     - "main"
    paths:
     - 'infrastructure/terraform/**'
     - 'infrastructure/kubernetes/**'

env:
  AWS_REGION: eu-central-1                                     
   

jobs:
  Cloud_Resources_Deployment:
    name: 'Cloud_Resources_Deployment'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Detect_Changes
      uses: dorny/paths-filter@v2
      id: changes
      with:

        base: 'main'

        filters: |
          terraform:
            - 'infrastructure/terraform/**'
          kubernetes:
            - 'infrastructure/kubernetes/**'

    - name: Setup_Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: terraform
      if: steps.changes.outputs.terraform == 'true' 
      run: |
            echo "this terraform specific deployment"
            bash deploy.sh
            

    - name: secret_manager_accessor_configuration
      if: steps.changes.outputs.kubernetes == 'true' 
      run: |
            echo "this terraform specific deployment"
            bash secret_manager.sh
            


    - name: kubernetes
      if: steps.changes.outputs.kubernetes == 'true' 
      run: |
            echo "this kubernetes specific deployment"
            aws --version
            aws eks --version
            aws s3api get-bucket-location --bucket llm-terraform-backend  --region eu-central-1 
            kubectl version
            

    